### ISSUE TITLE
Cachemanager::getUnlockedConfiguration does not honour cid value

### ISSUE THREAD

**Issue by ned21** [quattor/CCM#38]
ncm-query --useprofile N calls this sequence of methods:

```
$self->{'CACHEMGR'}=EDG::WP4::CCM::CacheManager->new($cacheroot);
$self->{'CCM_CONFIG'}=$self->{'CACHEMGR'}->getUnlockedConfiguration($cred,$profileID);
```

which results in the correct CID being set in the cachemanager object. However, when ncm-query then calls getElement, the value returned is always from the latest profile.

**Comment by stdweird** [comment]
although normal behaviour for `unlocked` configuration instance, it makes no sense to use an unlocked instance with the `--useprofile` support (so i'd say this is a `ncm-query` issue).
it might be good to know which options of `ncm-query` are being used in the wild, since i'm going to make a `ccm-cli` february/march timeframe.

**Comment by ned21** [comment]
@stdweird - I don't follow. ncm-query always uses unlocked configuration instance, why would it need to use locking when using --useprofile?

**Comment by stdweird** [comment]
because an unlocked configuration always gives the latest CID (that's what the locking is about).

**Comment by ned21** [comment]
OK, so this issue is that passing $cid to UnlockedConfiguration should be an error, and I filed a new issue against ncm-query for the --useprofile bug. https://github.com/quattor/ncm-query/issues/8

**Comment by stdweird** [comment]
@ned21 https://github.com/stdweird/CCM/commit/82dfb116797e70709db4e4e3723f9c58f047fb39 hopefully makes the meaning of "locked Configuration" clearer.

**Comment by stdweird** [comment]
@ned21 i added a smarted `getConfiguration` https://github.com/stdweird/CCM/commit/b7ea01653b24dec3351048e755b7687d4c4ee2c4 ; that's probably what `ncm-query` should use

**Comment by ned21** [comment]
Excellent! I will look out for the PR.

**Comment by stdweird** [comment]
@ned21 the PR you are looking out for is #61 (which is merged)

**Comment by ned21** [comment]
So is this fixed by #61 and the underlying problem I saw remains open in quattor/ncm-query#8?

**Comment by stdweird** [comment]
@ned21 define "fixed". the PR hopefully made it more clear what an unlocked configuration is, and provides an easier/smarter API to get Configuration instances.
but the underlying problem still remains: passing a cid to get an unlocked configuration makes no sense.

**Comment by stdweird** [comment]
@jrha i have no intention of ever touching `ncm-query` again (unless someone adds unittests first that is), i'll see if this works in new CLI.

**Comment by stdweird** [comment]
works fine with latest ccm CLI (28 is current on this box)
```
[root@master1 ~]# ccm --showcids
26,27,28
[root@master1 ~]# diff /var/lib/ccm/profile.26/profile.xml /var/lib/ccm/profile.27/profile.xml | tail 
---
>         "_36_2e0_2dug_2e1452096728_2ee63a275_2ecgroups": {
4788c4788
<             "url": "http://geodude.ugent.be/20151201/torque42-el7"
---
>             "url": "http://geodude.ugent.be//torque42-el7"
5206c5206
<     "quattorid": "wpoelman-snoopy-1452014885",
---
>     "quattorid": "stdweird-t6_pt2-1452100535",
[root@master1 ~]# ccm --cid 26 / >& out26
[root@master1 ~]# ccm --cid 27 / >& out27
[root@master1 ~]# diff out26 out27 |tail
---
>         +-6.0-ug.1452096728.e63a275.cgroups
3914c3915
<             $ url : 'http://geodude.ugent.be/20151201/torque42-el7'
---
>             $ url : 'http://geodude.ugent.be//torque42-el7'
4248c4249
<     $ quattorid : 'wpoelman-snoopy-1452014885'
---
>     $ quattorid : 'stdweird-t6_pt2-1452100535'
```

**Comment by jrha** [comment]
Good enough for me... @ned21?

**Comment by ned21** [comment]
https://github.com/quattor/CCM/blob/master/src/main/perl/Configuration.pm#L70 says that an unlocked config alway uses the current CID, and getConfiguration does the right thing. Anyone using getUnlockedConfiguration method will get the "wrong" result so an update to https://github.com/quattor/CCM/blob/master/src/main/perl/CacheManager.pm#L315 to say that the $cid parameter is ignored and this method is deprecated in favour of getConfiguration would be enough to close this.
